plugin.id=plugin-client-cert
plugin.name=Client Certificate Plugin
plugin.version=${project.version}
plugin.entryClass=com.laker.postman.plugin.clientcert.ClientCertificatePlugin
plugin.description=Client certificate management and mTLS key material loading.
plugin.homepage=https://github.com/lakernote/easy-postman
plugin.minAppVersion=${plugin.minAppVersion}
