package com.laker.postman.model;

public enum Category {
    PRE_SCRIPT, ASSERT, EXTRACT, LOCAL_VAR, ENV_VAR, ENCODE,
    ENCRYPT, STRING, ARRAY, JSON, DATE, REGEX, LOG, CONTROL, TOKEN, COOKIES, OTHER,
    // 内置库分类
    CRYPTOJS, LODASH, MOMENT, EXAMPLES
}
