plugin.id=plugin-kafka
plugin.name=Kafka Plugin
plugin.version=${project.version}
plugin.entryClass=com.laker.postman.plugin.kafka.KafkaPlugin
plugin.description=Kafka toolbox panel, pm.kafka script API, completions and snippets.
plugin.homepage=https://github.com/lakernote/easy-postman
plugin.minAppVersion=${plugin.minAppVersion}
